### PR TITLE
Fix connect HOC on FilterPanelContent

### LINKED ISSUE #101: Range does not reset
When I try to reset the range control, its value doesn't change.

Sep-11-2019 10-01-56

### PR DESCRIPTION
**Pull request by SebCorbin**
I've put back `context` and `props`,  it makes the thing more understandable

Fixes #101 #80

### CODE REVIEW

File: src/modules/Visualizer/LayersTree/LayersTreeItem/FiltersPanel/FiltersPanelContent/index.js [hunk 1]
```diff
@@ -2,13 +2,16 @@ import FiltersPanelContent from './FiltersPanelContent';
 
 import { connectLayersTree } from '../../../LayersTreeProvider/context';
 
-export default connectLayersTree('translate', ({ getLayerState }, { layer, layer: { exclusive, layers } }) => {
+export default connectLayersTree((context, props) => {
```
Comment (hadrienl) [inline src/modules/Visualizer/LayersTree/LayersTreeItem/FiltersPanel/FiltersPanelContent/index.js]:
```suggestion
export default connectLayersTree(({ getLayerState, translate }, { layer, layer: { exclusive, layers } }) => {
```
